/* ===== Aniimo Creature Database =====
 * Data sourced from aniimotools.dev & wiki.aniimo.com
 * Beta build values — may be retuned at launch.
 * Verified: 2026-07-25
 */
var CREATURES = [
{no:"001",name:"Emberpup",nameZh:"炽焰犬",el:"fire",el2:null,role:"DPS",stage:"Lumin",hp:67,brk:38,atk:86,pdef:60,mdef:53,regen:67,
 desc:"活泼的小家伙，喜欢跟着 Flameruff 跑。一旦身上的焦毛开始燃烧，就会变得生龙活虎。",
 descEn:"Lively creatures that follow Flameruffs around. Once the smoldering fur starts to burn, they thrive.",
 forms:"Basic / Highland / Mountain Woods",evo:["002","003","004"],
 traits:[{n:"Scorching Flames",nZh:"灼烧烈焰",d:"对有≥5层火异常的目标伤害+15%"},{n:"Born Ready",nZh:"蓄势待发",d:"8秒内未释放技能时，下次技能伤害+25%"}],
 skills:[{n:"Fire Kick",nZh:"火焰踢",t:"Physical",el:"fire",pw:72,ep:0},{n:"ATK",nZh:"普攻",t:"Physical",el:"fire",pw:6,ep:0},{n:"Pebble Kick",nZh:"碎石踢",t:"Physical",el:"earth",pw:72,ep:0},{n:"Fire Bolt",nZh:"火焰箭",t:"Magical",el:"fire",pw:30,ep:10}],
 habitats:["Nimbus Fields","Mistwoods","Argent Strait","Echoback Landing","Beast Fang Ridge"]},
{no:"002",name:"Flameruff",nameZh:"燃绒犬",el:"fire",el2:null,role:"DPS",stage:"Gamma",hp:81,brk:45,atk:104,pdef:72,mdef:63,regen:80,
 desc:"炽焰犬的进化形态。Gamma 阶段，攻击和血量更高。",
 descEn:"Evolved form of Emberpup. Gamma stage with higher ATK and HP.",
 forms:"Basic / Highland / Mountain Woods",evo:["003","004"],
 traits:[],skills:[],habitats:[]},
{no:"003",name:"Scorchhowl",nameZh:"炽嚎",el:"fire",el2:null,role:"DPS",stage:"Nova",hp:90,brk:50,atk:115,pdef:80,mdef:70,regen:90,
 desc:"热衷于战斗的快感，火焰与灼烧印记见证其成长。Nova 阶段，拥有雷暴形态和棱晶形态。",
 descEn:"They enjoy the thrill of the fight since flame and burning mark their growth. Nova stage with Thunderstorm and Prismana forms.",
 forms:"Normal / Thunderstorm / Prismana / Highland / Mountain Woods / Umbrabow",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"004",name:"Inferlupa",nameZh:"炼狱狼",el:"fire",el2:null,role:"Break",stage:"Nova",hp:95,brk:113,atk:89,pdef:70,mdef:80,regen:104,
 desc:"Flameruff 线的 Nova 分支进化，需完成多日剧情任务解锁。火系中 BREAK 最高。",
 descEn:"Alternate Nova evolution of the Flameruff line, gated behind a multi-day narrative quest. Highest BREAK in the fire roster.",
 forms:"Normal",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"005",name:"Celestis",nameZh:"星角",el:"dark",el2:null,role:"DPS",stage:"Basic Form",hp:77,brk:42,atk:106,pdef:54,mdef:57,regen:76,
 desc:"是个吃货！夜间在森林觅食时，头顶的发光星角常被误认为流星。",
 descEn:"They love food! When searching the forest for food, the glowing stars on their heads are often mistaken for comets.",
 forms:"Normal",evo:["006"],
 traits:[],skills:[],habitats:[]},
{no:"006",name:"Stellarys",nameZh:"星辉",el:"dark",el2:null,role:"DPS",stage:"Nova",hp:90,brk:50,atk:125,pdef:63,mdef:67,regen:90,
 desc:"星角的 Nova 进化。攻击力125，暗系最高 raw ATK。",
 descEn:"Nova evolution of Celestis. ATK 125, highest raw attack in the dark roster.",
 forms:"Normal / Rainstorm / Prismana / Umbrabow",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"007",name:"Chirpi",nameZh:"啾啾鸟",el:"wind",el2:null,role:"Support",stage:"Basic Form",hp:96,brk:43,atk:75,pdef:67,mdef:69,regen:93,
 desc:"小型风属性辅助伊莫。血量96，魔防不错。",
 descEn:"Small wind-type support Aniimo. High HP (96) and decent M.DEF for its stage.",
 forms:"Basic / Highland / Mountain Woods",evo:["008"],
 traits:[],skills:[],habitats:[]},
{no:"008",name:"Tromber",nameZh:"鼓风鸟",el:"wind",el2:null,role:"Support",stage:"Basic Form",hp:113,brk:51,atk:88,pdef:79,mdef:81,regen:110,
 desc:"风属性辅助伊莫，血量113，回复110，出色的续航能力。",
 descEn:"Wind support Aniimo with HP 113 and REGEN 110 — excellent sustain.",
 forms:"Basic / Highland / Mountain Woods",evo:["009"],
 traits:[],skills:[],habitats:[]},
{no:"009",name:"Cornet",nameZh:"短角鸟",el:"wind",el2:null,role:"DPS",stage:"—",hp:93,brk:50,atk:121,pdef:66,mdef:65,regen:94,
 desc:"风属性输出伊莫，攻击力121，高伤害输出。",
 descEn:"Wind DPS Aniimo with ATK 121 — high damage output.",
 forms:"Basic / Highland / Prismana / Mountain Woods / Umbrabow",evo:["010"],
 traits:[],skills:[],habitats:[]},
{no:"010",name:"Tubster",nameZh:"圆桶兽",el:"wind",el2:null,role:"Break",stage:"Nova",hp:108,brk:101,atk:75,pdef:61,mdef:110,regen:80,
 desc:"健壮的破防伊莫，BREAK 101，血量108。Alpha 战推荐使用。",
 descEn:"A sturdy Break Aniimo with BREAK 101 and HP 108. Recommended for Alpha battles.",
 forms:"Normal / Highland / Mountain Woods",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"011",name:"Iris",nameZh:"鸢尾",el:"grass",el2:null,role:"DPS",stage:"—",hp:69,brk:50,atk:101,pdef:53,mdef:53,regen:71,
 desc:"草属性输出伊莫，攻击力101。",
 descEn:"Grass DPS Aniimo with ATK 101.",
 forms:"Basic / Highland / Mountain Woods / Thunderstorm / Mudflat / Rainstorm / Prismana",evo:["012"],
 traits:[],skills:[],habitats:[]},
{no:"012",name:"Irisal",nameZh:"鸢尾花",el:"grass",el2:null,role:"DPS",stage:"—",hp:100,brk:50,atk:116,pdef:70,mdef:70,regen:98,
 desc:"鸢尾的进化形态，攻击力116，属性全面提升。",
 descEn:"Evolved form of Iris. ATK 116, all-around stat improvement.",
 forms:"Basic / Highland / Mountain Woods / Thunderstorm / Mudflat / Rainstorm / Prismana",evo:["013"],
 traits:[],skills:[],habitats:[]},
{no:"013",name:"Irisalis",nameZh:"鸢尾蝶",el:"grass",el2:null,role:"DPS",stage:"—",hp:102,brk:50,atk:130,pdef:80,mdef:80,regen:108,
 desc:"草系顶级输出，攻击力130，总属性550。",
 descEn:"Top-tier grass DPS, ATK 130, total stats 550.",
 forms:"Normal",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"014",name:"Skippy",nameZh:"跳跳兔",el:"water",el2:null,role:"Heal",stage:"Lumin",hp:69,brk:50,atk:54,pdef:45,mdef:66,regen:48,
 desc:"水属性治疗伊莫，前期过渡使用。",
 descEn:"Water healer Aniimo, early-game transition pick.",
 forms:"Basic / Highland / Mountain Woods",evo:["015"],
 traits:[],skills:[],habitats:[]},
{no:"015",name:"Pranky",nameZh:"淘气蛙",el:"water",el2:null,role:"Heal",stage:"Gamma",hp:106,brk:45,atk:81,pdef:65,mdef:99,regen:72,
 desc:"水属性治疗伊莫，Gamma阶段，血量106。",
 descEn:"Water healer, Gamma stage. HP 106 with solid M.DEF.",
 forms:"Basic / Highland / Mountain Woods",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"016",name:"Glacy",nameZh:"冰璃",el:"water",el2:"ice",role:"Heal",stage:"Basic Form",hp:118,brk:50,atk:90,pdef:72,mdef:110,regen:80,
 desc:"水冰双属性治疗。血量118，防御面扎实。",
 descEn:"Dual-type healer with Water and Ice. HP 118, solid defensive stats.",
 forms:"Basic / Highland / Prismana",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"017",name:"Leafy",nameZh:"叶叶",el:"grass",el2:"water",role:"Regen",stage:"Nova",hp:120,brk:50,atk:90,pdef:82,mdef:82,regen:106,
 desc:"草水双属性回复伊莫。血量120、回复106——长线作战顶级续航。",
 descEn:"Dual-type regen Aniimo. HP 120 and REGEN 106 — exceptional sustain for long fights.",
 forms:"Normal",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"018",name:"Nimbi",nameZh:"浮云",el:"wind",el2:null,role:"Support",stage:"Lumin",hp:80,brk:43,atk:76,pdef:68,mdef:82,regen:93,
 desc:"成群漂浮在草地上空，看到它们在云间飘荡也别惊讶。拥有暴雨形态。",
 descEn:"Don't be surprised to see them floating in the clouds in small groups above the grasslands. Has a Rainstorm form.",
 forms:"Normal / Highland / Mountain Woods / Thunderstorm",evo:["019"],
 traits:[],skills:[],habitats:[]},
{no:"019",name:"Turbo",nameZh:"旋风",el:"wind",el2:null,role:"Support",stage:"—",hp:95,brk:50,atk:90,pdef:80,mdef:96,regen:109,
 desc:"风属性辅助伊莫，回复109，出色的辅助能力。",
 descEn:"Wind support Aniimo with REGEN 109 — excellent support capability.",
 forms:"Basic / Highland / Mountain Woods / Prismana / Thunderstorm / Umbrabow",evo:["020"],
 traits:[],skills:[],habitats:[]},
{no:"020",name:"Dreaple",nameZh:"梦龙",el:"dark",el2:null,role:"Support",stage:"Nova",hp:120,brk:55,atk:90,pdef:77,mdef:108,regen:80,
 desc:"暗属性辅助伊莫，Nova阶段，血量120，魔防108。",
 descEn:"Dark support Aniimo, Nova stage. HP 120, M.DEF 108.",
 forms:"Normal",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"021",name:"Hummin",nameZh:"蜂鸟",el:"grass",el2:null,role:"Break",stage:"Lumin",hp:94,brk:80,atk:60,pdef:70,mdef:94,regen:60,
 desc:"草属性破防伊莫，血量94，魔防94。",
 descEn:"Grass Break Aniimo. HP 94, M.DEF 94.",
 forms:"Basic / Highland / Mountain Woods",evo:["022"],
 traits:[],skills:[],habitats:[]},
{no:"022",name:"Witchin",nameZh:"巫草",el:"dark",el2:null,role:"Regen",stage:"Basic Form",hp:115,brk:50,atk:80,pdef:80,mdef:90,regen:115,
 desc:"暗属性回复伊莫，血量115，回复115，顶级续航。",
 descEn:"Dark regen Aniimo. HP 115, REGEN 115 — top-tier sustain.",
 forms:"Basic / Highland / Prismana / Umbrabow",evo:["023"],
 traits:[],skills:[],habitats:[]},
{no:"023",name:"Tuckin",nameZh:"吞吞兽",el:"grass",el2:null,role:"Break",stage:"Nova",hp:106,brk:100,atk:80,pdef:83,mdef:110,regen:71,
 desc:"草属性破防伊莫，Nova阶段，BREAK 100，血量106。",
 descEn:"Grass Break Aniimo, Nova stage. BREAK 100, HP 106.",
 forms:"Normal / Highland",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"024",name:"Budclaw",nameZh:"芽爪",el:"earth",el2:"grass",role:"Break",stage:"—",hp:76,brk:84,atk:64,pdef:93,mdef:65,regen:72,
 desc:"终身一伴，总是成对出现。壳顶的心形花苞是它们幸福程度的指示器。",
 descEn:"Mates for life, always found in pairs. The heartbloom atop their shells indicates their happiness.",
 forms:"Normal / Highland / Mountain Woods / Thunderstorm",evo:["025"],
 traits:[],skills:[],habitats:[]},
{no:"025",name:"Shrubclaw",nameZh:"灌木爪",el:"earth",el2:null,role:"Break",stage:"Basic Form",hp:90,brk:99,atk:75,pdef:109,mdef:77,regen:85,
 desc:"土属性破防伊莫，物防109，出色的防御能力。",
 descEn:"Earth Break Aniimo. P.DEF 109 — excellent defensive stats.",
 forms:"Basic / Highland / Mountain Woods / Thunderstorm",evo:["026"],
 traits:[],skills:[],habitats:[]},
{no:"026",name:"Geoclaw",nameZh:"岩爪",el:"ice",el2:null,role:"Break",stage:"Nova",hp:93,brk:103,atk:80,pdef:113,mdef:79,regen:82,
 desc:"冰属性破防伊莫，Nova阶段，物防113，BREAK 103。",
 descEn:"Ice Break Aniimo, Nova stage. P.DEF 113, BREAK 103.",
 forms:"Normal",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"027",name:"Sparki",nameZh:"火花",el:"fire",el2:null,role:"Regen",stage:"—",hp:68,brk:41,atk:92,pdef:60,mdef:67,regen:98,
 desc:"火属性回复伊莫，攻击力92，回复98。",
 descEn:"Fire regen Aniimo. ATK 92, REGEN 98.",
 forms:"Basic / Highland / Mountain Woods / Thunderstorm",evo:["028"],
 traits:[],skills:[],habitats:[]},
{no:"028",name:"Flamerion",nameZh:"烈焰狮",el:"fire",el2:null,role:"Regen",stage:"Nova",hp:80,brk:50,atk:108,pdef:70,mdef:79,regen:115,
 desc:"火属性回复伊莫，Nova阶段，攻击力108，回复115。",
 descEn:"Fire regen Aniimo, Nova stage. ATK 108, REGEN 115.",
 forms:"Normal / Highland / Mountain Woods / Thunderstorm",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"029",name:"Flutternym",nameZh:"飞蝶",el:"wind",el2:null,role:"Heal",stage:"Basic Form",hp:94,brk:41,atk:81,pdef:68,mdef:68,regen:85,
 desc:"风属性治疗伊莫，血量94。",
 descEn:"Wind healer Aniimo. HP 94.",
 forms:"Basic / Highland / Mountain Woods / Thunderstorm",evo:["030"],
 traits:[],skills:[],habitats:[]},
{no:"030",name:"Gracewing",nameZh:"优雅翼",el:"wind",el2:null,role:"Heal",stage:"—",hp:110,brk:50,atk:95,pdef:80,mdef:80,regen:100,
 desc:"风属性治疗伊莫，血量110，回复100。",
 descEn:"Wind healer Aniimo. HP 110, REGEN 100.",
 forms:"Basic / Highland / Mountain Woods / Thunderstorm",evo:["031"],
 traits:[],skills:[],habitats:[]},
{no:"031",name:"Somniwing",nameZh:"梦翼",el:"wind",el2:null,role:"Regen",stage:"Basic Form",hp:111,brk:50,atk:92,pdef:80,mdef:80,regen:115,
 desc:"风属性回复伊莫，血量111，回复115。能量球技能每0.6秒消耗10EP。",
 descEn:"Wind regen Aniimo. HP 111, REGEN 115. Energy Orb skill consumes 10 EP per 0.6s.",
 forms:"Normal",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"032",name:"Eko",nameZh:"回音",el:"wind",el2:null,role:"Support",stage:"Basic Form",hp:70,brk:42,atk:112,pdef:70,mdef:57,regen:89,
 desc:"风属性辅助伊莫，攻击力112。",
 descEn:"Wind support Aniimo. ATK 112.",
 forms:"Normal",evo:["033"],
 traits:[],skills:[],habitats:[]},
{no:"033",name:"Eklue",nameZh:"回响",el:"wind",el2:null,role:"Support",stage:"Nova",hp:82,brk:49,atk:132,pdef:83,mdef:67,regen:105,
 desc:"风属性辅助伊莫，Nova阶段，攻击力132，图鉴最高ATK。",
 descEn:"Wind support Aniimo, Nova stage. ATK 132 — highest ATK in the codex.",
 forms:"Normal",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"034",name:"Budsquire",nameZh:"芽骑士",el:"grass",el2:null,role:"DPS",stage:"Basic Form",hp:82,brk:43,atk:103,pdef:59,mdef:59,regen:78,
 desc:"草属性输出伊莫，攻击力103。",
 descEn:"Grass DPS Aniimo. ATK 103.",
 forms:"Basic / Highland",evo:["035"],
 traits:[],skills:[],habitats:[]},
{no:"035",name:"Thornblade",nameZh:"荆刃",el:"grass",el2:null,role:"DPS",stage:"Nova",hp:96,brk:50,atk:121,pdef:70,mdef:70,regen:92,
 desc:"草属性输出伊莫，Nova阶段，攻击力121。",
 descEn:"Grass DPS Aniimo, Nova stage. ATK 121.",
 forms:"Normal / Rainstorm / Prismana / Highland / Umbrabow",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"036",name:"Melloblum",nameZh:"蜜花",el:"grass",el2:null,role:"Support",stage:"Nova",hp:95,brk:91,atk:108,pdef:70,mdef:70,regen:78,
 desc:"草属性辅助伊莫，Nova阶段，攻击力108。",
 descEn:"Grass support Aniimo, Nova stage. ATK 108.",
 forms:"Normal",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"037",name:"Pomegg",nameZh:"果蛋",el:"grass",el2:null,role:"Break",stage:"Basic Form",hp:74,brk:91,atk:72,pdef:68,mdef:65,regen:85,
 desc:"草属性破防伊莫，BREAK 91。",
 descEn:"Grass Break Aniimo. BREAK 91.",
 forms:"Basic / Highland / Mountain Woods / Thunderstorm",evo:["038"],
 traits:[],skills:[],habitats:[]},
{no:"038",name:"Dazmand",nameZh:"达兹曼",el:"electric",el2:null,role:"Support",stage:"Nova",hp:100,brk:91,atk:108,pdef:81,mdef:81,regen:71,
 desc:"电属性辅助伊莫，Nova阶段，攻击力108，血量100。",
 descEn:"Electric support Aniimo, Nova stage. ATK 108, HP 100.",
 forms:"Normal",evo:["039"],
 traits:[],skills:[],habitats:[]},
{no:"039",name:"Pomawk",nameZh:"果爪",el:"grass",el2:null,role:"Break",stage:"Nova",hp:87,brk:107,atk:85,pdef:80,mdef:76,regen:100,
 desc:"草属性破防伊莫，Nova阶段，BREAK 107，回复100。",
 descEn:"Grass Break Aniimo, Nova stage. BREAK 107, REGEN 100.",
 forms:"Normal / Highland / Mountain Woods / Thunderstorm",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"040",name:"Dewy",nameZh:"露珠",el:"dark",el2:null,role:"Support",stage:"Basic Form",hp:71,brk:69,atk:90,pdef:58,mdef:55,regen:94,
 desc:"暗属性辅助伊莫，回复94。",
 descEn:"Dark support Aniimo. REGEN 94.",
 forms:"Normal",evo:["041"],
 traits:[],skills:[],habitats:[]},
{no:"041",name:"Fragrancier",nameZh:"香氛师",el:"dark",el2:null,role:"Support",stage:"Nova",hp:84,brk:81,atk:106,pdef:68,mdef:65,regen:110,
 desc:"暗属性辅助伊莫，Nova阶段，攻击力106，回复110。",
 descEn:"Dark support Aniimo, Nova stage. ATK 106, REGEN 110.",
 forms:"Normal",evo:["042"],
 traits:[],skills:[],habitats:[]},
{no:"042",name:"Wisptis",nameZh:"幽火",el:"dark",el2:null,role:"DPS",stage:"Basic Form",hp:77,brk:43,atk:108,pdef:60,mdef:54,regen:77,
 desc:"暗属性输出伊莫，攻击力108。",
 descEn:"Dark DPS Aniimo. ATK 108.",
 forms:"Basic / Highland / Mountain Woods",evo:["043"],
 traits:[],skills:[],habitats:[]},
{no:"043",name:"Ignitis",nameZh:"暗袭",el:"dark",el2:null,role:"DPS",stage:"Nova",hp:90,brk:50,atk:128,pdef:70,mdef:63,regen:91,
 desc:"耐心潜伏在暗影中，等待最佳时机发动致命一击。攻击力128，顶级暗系输出。",
 descEn:"They patiently wait in the shadows for the right moment to deliver a deadly strike. ATK 128, top-tier dark DPS.",
 forms:"Normal / Highland / Prismana / Mountain Woods / Umbrabow",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"044",name:"Fulmintis",nameZh:"雷暗",el:"electric",el2:null,role:"DPS",stage:"Nova",hp:99,brk:50,atk:130,pdef:66,mdef:70,regen:105,
 desc:"电属性输出伊莫，Nova阶段，攻击力130，图鉴最高ATK之一。",
 descEn:"Electric DPS Aniimo, Nova stage. ATK 130 — one of the highest ATK in the codex.",
 forms:"Normal / Prismana",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"045",name:"Bonesky",nameZh:"骨空",el:"ice",el2:null,role:"DPS",stage:"—",hp:71,brk:38,atk:88,pdef:56,mdef:57,regen:67,
 desc:"冰属性输出伊莫，攻击力88。",
 descEn:"Ice DPS Aniimo. ATK 88.",
 forms:"Basic / Highland",evo:["046"],
 traits:[],skills:[],habitats:[]},
{no:"046",name:"Fenrier",nameZh:"霜狼",el:"ice",el2:null,role:"DPS",stage:"Lumin",hp:86,brk:45,atk:105,pdef:68,mdef:68,regen:81,
 desc:"冰属性输出伊莫，Lumin阶段，攻击力105。",
 descEn:"Ice DPS Aniimo, Lumin stage. ATK 105.",
 forms:"Basic / Highland",evo:["047"],
 traits:[],skills:[],habitats:[]},
{no:"047",name:"Glynsera",nameZh:"冰晶鹿",el:"ice",el2:null,role:"DPS",stage:"Lumin",hp:95,brk:50,atk:117,pdef:75,mdef:76,regen:90,
 desc:"冰属性输出伊莫，Lumin阶段，攻击力117，总属性503。",
 descEn:"Ice DPS Aniimo, Lumin stage. ATK 117, total 503.",
 forms:"Normal / Prismana / Highland",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"048",name:"Bolty",nameZh:"电光",el:"electric",el2:null,role:"Break",stage:"Lumin",hp:85,brk:87,atk:85,pdef:60,mdef:60,regen:73,
 desc:"电属性破防伊莫，Lumin阶段，BREAK 87。",
 descEn:"Electric Break Aniimo, Lumin stage. BREAK 87.",
 forms:"Basic / Highland",evo:["049"],
 traits:[],skills:[],habitats:[]},
{no:"049",name:"Blazen",nameZh:"烈电",el:"electric",el2:null,role:"Break",stage:"Lumin",hp:100,brk:104,atk:100,pdef:70,mdef:70,regen:86,
 desc:"电属性破防伊莫，Lumin阶段，BREAK 104，血量100。",
 descEn:"Electric Break Aniimo, Lumin stage. BREAK 104, HP 100.",
 forms:"Basic / Prismana / Highland / Umbrabow",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"050",name:"Susuta",nameZh:"潜猪",el:"water",el2:null,role:"Break",stage:"Lumin",hp:81,brk:72,atk:61,pdef:53,mdef:80,regen:64,
 desc:"到处挖土找礼物想送给心仪对象，但因为太害羞总是表白失败。",
 descEn:"They dig around to search for gifts to give to their crushes, but their wooing always fails because they are so shy.",
 forms:"Normal / Highland",evo:["051"],
 traits:[],skills:[],habitats:[]},
{no:"051",name:"Popota",nameZh:"泡泡猪",el:"water",el2:null,role:"Break",stage:"—",hp:92,brk:80,atk:96,pdef:68,mdef:68,regen:67,
 desc:"水属性破防伊莫，BREAK 80。",
 descEn:"Water Break Aniimo. BREAK 80.",
 forms:"Basic / Highland",evo:["052"],
 traits:[],skills:[],habitats:[]},
{no:"052",name:"Piopiota",nameZh:"噗噗猪",el:"water",el2:null,role:"Support",stage:"—",hp:102,brk:98,atk:108,pdef:75,mdef:75,regen:74,
 desc:"水属性辅助伊莫，攻击力108，BREAK 98。",
 descEn:"Water support Aniimo. ATK 108, BREAK 98.",
 forms:"Basic / Highland",evo:["053"],
 traits:[],skills:[],habitats:[]},
{no:"053",name:"Panpanta",nameZh:"潘潘塔",el:"water",el2:null,role:"Break",stage:"—",hp:104,brk:100,atk:85,pdef:70,mdef:106,regen:80,
 desc:"水属性破防伊莫，血量104，魔防106，BREAK 100。",
 descEn:"Water Break Aniimo. HP 104, M.DEF 106, BREAK 100.",
 forms:"Normal / Highland / Prismana",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"054",name:"Shelly",nameZh:"贝壳酱",el:"water",el2:null,role:"DPS",stage:"Basic Form",hp:75,brk:39,atk:90,pdef:56,mdef:56,regen:66,
 desc:"水系输出，属性均衡。收集贝壳酱可以揭开神秘生态档案的秘密。",
 descEn:"Water DPS with balanced stats. Gather Shelly to unveil the secrets of mystical ecological archives.",
 forms:"Normal",evo:["055"],
 traits:[],skills:[],habitats:[]},
{no:"055",name:"Sheldon",nameZh:"谢尔登",el:"water",el2:null,role:"DPS",stage:"Basic Form",hp:90,brk:44,atk:109,pdef:68,mdef:68,regen:79,
 desc:"水属性输出伊莫，攻击力109。",
 descEn:"Water DPS Aniimo. ATK 109.",
 forms:"Normal",evo:["056"],
 traits:[],skills:[],habitats:[]},
{no:"056",name:"Sherro",nameZh:"谢罗",el:"water",el2:null,role:"DPS",stage:"Nova",hp:100,brk:50,atk:121,pdef:75,mdef:75,regen:88,
 desc:"水属性输出伊莫，Nova阶段，攻击力121。有 Alpha 变体。",
 descEn:"Water DPS Aniimo, Nova stage. ATK 121. Has Alpha variant.",
 forms:"Normal / Thunderstorm / Prismana / Umbrabow",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"057",name:"Baleetle",nameZh:"岩甲虫",el:"earth",el2:null,role:"DPS",stage:"Basic Form",hp:77,brk:42,atk:102,pdef:68,mdef:68,regen:85,
 desc:"土属性输出伊莫，攻击力102。",
 descEn:"Earth DPS Aniimo. ATK 102.",
 forms:"Basic / Highland",evo:["058"],
 traits:[],skills:[],habitats:[]},
{no:"058",name:"Waleetle",nameZh:"鲸甲虫",el:"earth",el2:null,role:"DPS",stage:"Nova",hp:90,brk:50,atk:120,pdef:80,mdef:80,regen:100,
 desc:"土属性输出伊莫，Nova阶段，攻击力120。",
 descEn:"Earth DPS Aniimo, Nova stage. ATK 120.",
 forms:"Normal / Highland",evo:["059"],
 traits:[],skills:[],habitats:[]},
{no:"059",name:"Bouldus",nameZh:"巨石兽",el:"earth",el2:null,role:"Support",stage:"Nova",hp:91,brk:52,atk:119,pdef:101,mdef:54,regen:104,
 desc:"土属性辅助伊莫，Nova阶段，攻击力119，物防101。",
 descEn:"Earth support Aniimo, Nova stage. ATK 119, P.DEF 101.",
 forms:"Normal / Highland",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"060",name:"Fentuft",nameZh:"绒尾",el:"electric",el2:null,role:"DPS",stage:"Basic Form",hp:85,brk:41,atk:106,pdef:60,mdef:60,regen:77,
 desc:"电属性输出伊莫，攻击力106。",
 descEn:"Electric DPS Aniimo. ATK 106.",
 forms:"Normal",evo:["061"],
 traits:[],skills:[],habitats:[]},
{no:"061",name:"Fenmane",nameZh:"鬃毛兽",el:"electric",el2:null,role:"DPS",stage:"—",hp:100,brk:50,atk:125,pdef:70,mdef:70,regen:90,
 desc:"电属性输出伊莫，攻击力125。",
 descEn:"Electric DPS Aniimo. ATK 125.",
 forms:"Normal / Prismana",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"062",name:"Helmut",nameZh:"盔甲兽",el:"dark",el2:null,role:"Break",stage:"Basic Form",hp:60,brk:60,atk:52,pdef:68,mdef:48,regen:51,
 desc:"暗属性破防伊莫，基础形态。",
 descEn:"Dark Break Aniimo, basic form.",
 forms:"Basic / Highland / Mountain Woods",evo:["063"],
 traits:[],skills:[],habitats:[]},
{no:"063",name:"Pawney",nameZh:"勇骑",el:"dark",el2:null,role:"DPS",stage:"—",hp:90,brk:55,atk:128,pdef:89,mdef:70,regen:80,
 desc:"手持断剑和铠甲，被勇气与力量祝福，守护伙伴、挑战强敌。攻击力128。",
 descEn:"Armed with a broken sword and armor, blessed with courage and might. ATK 128.",
 forms:"Normal / Highland / Mountain Woods / Prismana / Umbrabow",evo:["064"],
 traits:[],skills:[],habitats:[]},
{no:"064",name:"Rookey",nameZh:"暗骑",el:"dark",el2:"ice",role:"Break",stage:"Nova",hp:103,brk:105,atk:92,pdef:103,mdef:70,regen:75,
 desc:"暗/冰双属性破防伊莫，Nova阶段，BREAK 105，物防103。",
 descEn:"Dark/Ice dual-type Break Aniimo, Nova stage. BREAK 105, P.DEF 103.",
 forms:"Normal / Highland / Mountain Woods",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"065",name:"Jawling",nameZh:"颚狼",el:"wind",el2:null,role:"Break",stage:"Lumin",hp:79,brk:76,atk:64,pdef:83,mdef:51,regen:63,
 desc:"风属性破防伊莫，Lumin阶段。",
 descEn:"Wind Break Aniimo, Lumin stage.",
 forms:"Basic / Highland",evo:["066"],
 traits:[],skills:[],habitats:[]},
{no:"066",name:"Helmwhelp",nameZh:"盔幼龙",el:"wind",el2:null,role:"Break",stage:"Basic Form",hp:95,brk:92,atk:76,pdef:100,mdef:61,regen:76,
 desc:"风属性破防伊莫，物防100。",
 descEn:"Wind Break Aniimo. P.DEF 100.",
 forms:"Basic / Highland",evo:["067"],
 traits:[],skills:[],habitats:[]},
{no:"067",name:"Helgon",nameZh:"赫尔贡",el:"wind",el2:null,role:"Break",stage:"—",hp:105,brk:102,atk:85,pdef:111,mdef:68,regen:84,
 desc:"风属性破防伊莫，物防111，BREAK 102，总属性555。",
 descEn:"Wind Break Aniimo. P.DEF 111, BREAK 102, total 555.",
 forms:"Normal / Highland",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"068",name:"Infergon",nameZh:"炎龙",el:"fire",el2:null,role:"DPS",stage:"Nova",hp:100,brk:53,atk:114,pdef:81,mdef:98,regen:90,
 desc:"火属性输出伊莫，Nova阶段，攻击力114。",
 descEn:"Fire DPS Aniimo, Nova stage. ATK 114.",
 forms:"Normal",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"069",name:"Cubbo",nameZh:"熊宝",el:"earth",el2:null,role:"DPS",stage:"Basic Form",hp:92,brk:42,atk:107,pdef:71,mdef:62,regen:71,
 desc:"土属性输出伊莫，攻击力107。",
 descEn:"Earth DPS Aniimo. ATK 107.",
 forms:"Normal",evo:["070"],
 traits:[],skills:[],habitats:[]},
{no:"070",name:"Grizbo",nameZh:"灰熊",el:"earth",el2:null,role:"DPS",stage:"Lumin",hp:108,brk:50,atk:126,pdef:83,mdef:73,regen:84,
 desc:"土属性输出伊莫，Lumin阶段，攻击力126。",
 descEn:"Earth DPS Aniimo, Lumin stage. ATK 126.",
 forms:"Normal / Prismana",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"071",name:"Pebbling",nameZh:"碎石",el:"earth",el2:null,role:"Break",stage:"Basic Form",hp:83,brk:79,atk:68,pdef:52,mdef:74,regen:56,
 desc:"土属性破防伊莫，基础形态。",
 descEn:"Earth Break Aniimo, basic form.",
 forms:"Normal",evo:["072"],
 traits:[],skills:[],habitats:[]},
{no:"072",name:"Lavazar",nameZh:"熔岩虫",el:"fire",el2:"earth",role:"Break",stage:"Gamma",hp:99,brk:93,atk:82,pdef:63,mdef:89,regen:68,
 desc:"火/土双属性破防伊莫，Gamma阶段，BREAK 93。",
 descEn:"Fire/Earth dual-type Break Aniimo, Gamma stage. BREAK 93.",
 forms:"Normal",evo:["073"],
 traits:[],skills:[],habitats:[]},
{no:"073",name:"Magmarex",nameZh:"熔岩兽",el:"fire",el2:"dark",role:"Break",stage:"—",hp:110,brk:104,atk:91,pdef:70,mdef:99,regen:75,
 desc:"火/暗双属性破防伊莫，血量110，BREAK 104。",
 descEn:"Fire/Dark dual-type Break Aniimo. HP 110, BREAK 104.",
 forms:"Normal / Prismana / Umbrabow",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"074",name:"Geodeback",nameZh:"晶壳兽",el:"earth",el2:null,role:"Break",stage:"Nova",hp:99,brk:102,atk:81,pdef:89,mdef:54,regen:70,
 desc:"土属性破防伊莫，Nova阶段，BREAK 102。",
 descEn:"Earth Break Aniimo, Nova stage. BREAK 102.",
 forms:"Normal",evo:["075"],
 traits:[],skills:[],habitats:[]},
{no:"075",name:"Minespine",nameZh:"矿脊",el:"earth",el2:null,role:"Break",stage:"Nova",hp:110,brk:113,atk:90,pdef:99,mdef:60,regen:78,
 desc:"土属性破防伊莫，Nova阶段，血量110，BREAK 113，物防99。",
 descEn:"Earth Break Aniimo, Nova stage. HP 110, BREAK 113, P.DEF 99.",
 forms:"Normal",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"076",name:"Cozite",nameZh:"耐寒石",el:"earth",el2:null,role:"Support",stage:"—",hp:77,brk:50,atk:77,pdef:67,mdef:67,regen:100,
 desc:"土属性辅助伊莫，回复100。",
 descEn:"Earth support Aniimo. REGEN 100.",
 forms:"Normal",evo:["077"],
 traits:[],skills:[],habitats:[]},
{no:"077",name:"Bailite",nameZh:"拜石",el:"earth",el2:null,role:"Support",stage:"Basic Form",hp:75,brk:103,atk:114,pdef:85,mdef:84,regen:75,
 desc:"土属性辅助伊莫，攻击力114，BREAK 103。",
 descEn:"Earth support Aniimo. ATK 114, BREAK 103.",
 forms:"Normal",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"078",name:"Bulbly",nameZh:"球泡",el:"electric",el2:null,role:"Support",stage:"Basic Form",hp:83,brk:37,atk:68,pdef:63,mdef:63,regen:90,
 desc:"电属性辅助伊莫，回复90。",
 descEn:"Electric support Aniimo. REGEN 90.",
 forms:"Normal",evo:["079"],
 traits:[],skills:[],habitats:[]},
{no:"079",name:"Veilfloat",nameZh:"面纱浮",el:"electric",el2:null,role:"Support",stage:"Gamma",hp:99,brk:45,atk:81,pdef:77,mdef:77,regen:107,
 desc:"电属性辅助伊莫，Gamma阶段，回复107。",
 descEn:"Electric support Aniimo, Gamma stage. REGEN 107.",
 forms:"Normal",evo:["080"],
 traits:[],skills:[],habitats:[]},
{no:"080",name:"Luminelle",nameZh:"光精灵",el:"electric",el2:null,role:"Support",stage:"Nova",hp:110,brk:50,atk:90,pdef:85,mdef:85,regen:120,
 desc:"Nova 阶段辅助，血量110，回复120。世界中有 Alpha 变体可刷新挑战。",
 descEn:"Nova-stage support with HP 110 and REGEN 120. Has an Alpha variant that respawns in the world.",
 forms:"Normal / Rainstorm / Prismana / Umbrabow",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"081",name:"Fahloo",nameZh:"法流",el:"water",el2:null,role:"Regen",stage:"Basic Form",hp:102,brk:44,atk:76,pdef:68,mdef:76,regen:93,
 desc:"水属性回复伊莫，血量102，回复93。",
 descEn:"Water regen Aniimo. HP 102, REGEN 93.",
 forms:"Normal",evo:["082"],
 traits:[],skills:[],habitats:[]},
{no:"082",name:"Erlath",nameZh:"尔拉",el:"water",el2:null,role:"Regen",stage:"Basic Form",hp:120,brk:50,atk:90,pdef:80,mdef:90,regen:110,
 desc:"水属性回复伊莫，血量120，回复110。",
 descEn:"Water regen Aniimo. HP 120, REGEN 110.",
 forms:"Normal",evo:["083"],
 traits:[],skills:[],habitats:[]},
{no:"083",name:"Besauce",nameZh:"调味汁",el:"electric",el2:null,role:"Regen",stage:"Basic Form",hp:82,brk:90,atk:89,pdef:75,mdef:75,regen:110,
 desc:"电属性回复伊莫，回复110，BREAK 90。",
 descEn:"Electric regen Aniimo. REGEN 110, BREAK 90.",
 forms:"Normal",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"084",name:"Reefish",nameZh:"礁鱼",el:"earth",el2:null,role:"Regen",stage:"Basic Form",hp:83,brk:91,atk:66,pdef:75,mdef:79,regen:92,
 desc:"土属性回复伊莫，BREAK 91，回复92。",
 descEn:"Earth regen Aniimo. BREAK 91, REGEN 92.",
 forms:"Normal / Highland",evo:["085"],
 traits:[],skills:[],habitats:[]},
{no:"085",name:"Coraliz",nameZh:"珊瑚兽",el:"earth",el2:"water",role:"Regen",stage:"Basic Form",hp:98,brk:107,atk:78,pdef:88,mdef:93,regen:108,
 desc:"土水双属性回复，总属性572——当前图鉴中最高总属性。回复108。",
 descEn:"Dual-type regen with total stats 572 — the highest base total in the current roster. REGEN 108.",
 forms:"Normal / Highland",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"086",name:"Cheekie",nameZh:"顽皮兽",el:"ice",el2:null,role:"Break",stage:"Basic Form",hp:89,brk:92,atk:64,pdef:76,mdef:79,regen:88,
 desc:"冰属性破防伊莫，BREAK 92。",
 descEn:"Ice Break Aniimo. BREAK 92.",
 forms:"Normal",evo:["087"],
 traits:[],skills:[],habitats:[]},
{no:"087",name:"Wavwal",nameZh:"波涛兽",el:"ice",el2:null,role:"Break",stage:"Nova",hp:105,brk:110,atk:75,pdef:89,mdef:93,regen:103,
 desc:"Nova 阶段破防伊莫，总属性575，BREAK 110。目前图鉴中总属性最高。",
 descEn:"Nova-stage Break Aniimo with total stats 575, BREAK 110. Currently the highest total in the codex.",
 forms:"Normal",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"088",name:"Bubbeep",nameZh:"泡泡兔",el:"grass",el2:null,role:"Heal",stage:"—",hp:104,brk:43,atk:85,pdef:78,mdef:75,regen:82,
 desc:"草属性治疗伊莫，血量104。",
 descEn:"Grass healer Aniimo. HP 104.",
 forms:"Normal",evo:["089"],
 traits:[],skills:[],habitats:[]},
{no:"089",name:"Glameep",nameZh:"闪耀兔",el:"grass",el2:null,role:"Heal",stage:"—",hp:122,brk:50,atk:100,pdef:92,mdef:89,regen:97,
 desc:"草属性治疗伊莫，血量122，图鉴最高HP。",
 descEn:"Grass healer Aniimo. HP 122 — highest HP in the codex.",
 forms:"Normal",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"090",name:"Popapus",nameZh:"纸片怪",el:"water",el2:null,role:"DPS",stage:"—",hp:90,brk:45,atk:102,pdef:58,mdef:65,regen:90,
 desc:"水属性输出伊莫，攻击力102。",
 descEn:"Water DPS Aniimo. ATK 102.",
 forms:"Normal",evo:["091"],
 traits:[],skills:[],habitats:[]},
{no:"091",name:"Gachapus",nameZh:"卡恰怪",el:"water",el2:null,role:"DPS",stage:"—",hp:106,brk:51,atk:121,pdef:68,mdef:77,regen:106,
 desc:"水属性输出伊莫，攻击力121，血量106。",
 descEn:"Water DPS Aniimo. ATK 121, HP 106.",
 forms:"Normal",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"092",name:"Malangel",nameZh:"恶天使",el:"ice",el2:null,role:"DPS",stage:"—",hp:100,brk:50,atk:105,pdef:80,mdef:80,regen:100,
 desc:"冰属性输出伊莫，攻击力105，总属性515。",
 descEn:"Ice DPS Aniimo. ATK 105, total 515.",
 forms:"Normal",evo:["093"],
 traits:[],skills:[],habitats:[]},
{no:"093",name:"Malevsera",nameZh:"恶魔翼",el:"ice",el2:null,role:"DPS",stage:"Nova",hp:88,brk:52,atk:125,pdef:70,mdef:80,regen:110,
 desc:"冰属性输出伊莫，Nova阶段，攻击力125，回复110。",
 descEn:"Ice DPS Aniimo, Nova stage. ATK 125, REGEN 110.",
 forms:"Normal",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"—",name:"Helion",nameZh:"赫利昂",el:"light",el2:null,role:"Starter",stage:"—",hp:90,brk:85,atk:116,pdef:65,mdef:65,regen:83,
 desc:"两只特殊初始伊莫之一。总属性504，攻击力116，破防85。光属性。",
 descEn:"One of the two special starter Aniimo. Total stats 504, ATK 116, BREAK 85. Light element.",
 forms:"Starter",evo:[],
 traits:[],skills:[],habitats:[]},
{no:"—",name:"Lunara",nameZh:"露娜拉",el:"light",el2:null,role:"Starter",stage:"—",hp:90,brk:85,atk:116,pdef:65,mdef:65,regen:83,
 desc:"另一只特殊初始伊莫。属性与赫利昂相同（总属性504）。开局二选一。",
 descEn:"The other special starter. Same stats as Helion (504 total). Choose between Helion and Lunara at the start.",
 forms:"Starter",evo:[],
 traits:[],skills:[],habitats:[]}
];

/* Type effectiveness chart (non-bidirectional) */
var TYPE_CHART = {
  fire:    {grass:1.6, ice:1.6, fire:0.625, water:0.625, earth:0.625, light:0.625},
  water:   {fire:1.6, earth:1.6, water:0.625, grass:0.625, ice:0.625, light:0.625},
  grass:   {water:1.6, earth:1.6, fire:0.625, grass:0.625, light:0.625},
  electric:{water:1.6, wind:1.6, electric:0.625, ice:0.625, earth:0.625, light:0.625},
  ice:     {water:1.6, electric:1.6, fire:0.625, grass:0.625, ice:0.625, earth:0.625, wind:0.625},
  earth:   {electric:1.6, ice:1.6, water:0.625, grass:0.625, earth:0.625, dark:0.625},
  wind:    {grass:1.6, dark:1.6, electric:0.625, wind:0.625},
  light:   {wind:1.6, dark:1.6, electric:0.625, light:0.625},
  dark:    {fire:1.6, grass:1.6, light:1.6, water:0.625, wind:0.625, dark:0.625}
};

/* Tier list (based on total stats, role effectiveness, and community ratings) */
var TIER_LIST = {
  PvE: {
    SS: ["Wavwal","Coraliz","Minespine","Helgon","Inferlupa","Irisalis","Magmarex","Glameep","Tuckin","Geoclaw"],
    S:  ["Rookey","Panpanta","Tubster","Shrubclaw","Pomawk","Eklue","Fulmintis","Erlath","Luminelle","Scorchhowl"],
    A:  ["Ignitis","Stellarys","Malevsera","Sherro","Thornblade","Glynsera","Flamerion","Dreaple","Somniwing","Leafy","Helion","Lunara","Bouldus","Bailite","Grizbo","Infergon","Melloblum","Pawney","Turbo","Blazen"],
    B:  ["Cornet","Waleetle","Fenmane","Piopiota","Dazmand","Fragrancier","Besauce","Reefish","Cheekie","Glacy","Pranky","Witchin","Helmwhelp","Veilfloat","Gachapus","Malangel","Geodeback","Flameruff","Cubbo","Eklue"],
    C:  ["Sparki","Hummin","Sapota","Jawling","Dewy","Pomegg","Budsquire","Wisptis","Fentuft","Sheldon","Baleetle","Cozite","Bubbeep","Lavazar","Pebbling","Flutternym","Gracewing","Nimbi","Irisal","Chirpi","Tromber","Susuta","Popota","Skippy","Emberpup","Bonesky","Fenrier","Shelly","Helmut","Popapus","Bulbly"],
    D:  ["Eko","Iris"]
  },
  PvP: {
    SS: ["Ignitis","Pawney","Fulmintis","Eklue","Irisalis","Wavwal","Malevsera"],
    S:  ["Coraliz","Minespine","Helgon","Inferlupa","Magmarex","Rookey","Sherro","Glynsera","Gachapus","Glameep"],
    A:  ["Panpanta","Tubster","Stellarys","Thornblade","Flamerion","Tuckin","Geoclaw","Luminelle","Blazen","Dreaple","Somniwing","Leafy","Erlath","Grizbo","Infergon","Melloblum"],
    B:  ["Shrubclaw","Pomawk","Turbo","Fenmane","Piopiota","Dazmand","Fragrancier","Besauce","Reefish","Cheekie","Glacy","Pranky","Witchin","Helmwhelp","Veilfloat","Malangel","Geodeback","Flameruff","Cubbo","Helion","Lunara","Bouldus","Bailite","Scorchhowl","Cornet","Waleetle"],
    C:  ["Sparki","Hummin","Jawling","Dewy","Pomegg","Budsquire","Wisptis","Fentuft","Sheldon","Baleetle","Cozite","Bubbeep","Lavazar","Pebbling","Flutternym","Gracewing","Nimbi","Irisal","Chirpi","Tromber","Susuta","Popota","Skippy","Emberpup","Bonesky","Fenrier","Shelly","Helmut","Popapus","Bulbly","Eko","Iris"],
    D:  []
  }
};

/* Element display names */
var EL_NAMES = {
  fire:{zh:"火",en:"Fire"},water:{zh:"水",en:"Water"},grass:{zh:"草",en:"Grass"},
  electric:{zh:"电",en:"Lightning"},ice:{zh:"冰",en:"Ice"},earth:{zh:"土",en:"Earth"},
  wind:{zh:"风",en:"Wind"},light:{zh:"光",en:"Light"},dark:{zh:"暗",en:"Dark"}
};

/* Role display names */
var ROLE_NAMES = {
  DPS:{zh:"输出",en:"DPS"},Break:{zh:"破防",en:"Break"},Heal:{zh:"治疗",en:"Heal"},
  Support:{zh:"辅助",en:"Support"},Regen:{zh:"回复",en:"Regen"},Starter:{zh:"初始",en:"Starter"}
};
